<a href="https://colab.research.google.com/github/shiva-sharma05/NumPy/blob/main/numpy_assig_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [21]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(f"shape : {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"size : {arr.size}")
print(f"dtype: {arr.dtype}")

shape : (5,)
Dimensions: 1
size : 5
dtype: int64



# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [22]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)



# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [23]:
b = np.array([5,10,15,20,25])
print(b[0])
print(b[-1])

5
25



# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [24]:
c = np.array([[10,20,30],
 [40,50,60],
 [70,80,90]])
print(c[1,1])

50



# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [25]:
d = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])
print(d[2,2])

9



# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [26]:
e = np.array([10,20,30,40,50,60])
print(e[1:5])

[20 30 40 50]



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [27]:
f = np.array([1,2,3,4,5,6,7,8])
print(f[:5])

[1 2 3 4 5]



# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [28]:
g = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])
print(g[0:2 ,0:])

[[1 2 3]
 [4 5 6]]



# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [29]:
h = np.array([[10,20,30],
 [40,50,60],
 [70,80,90]])
print(h[:: , :2])

[[10 20]
 [40 50]
 [70 80]]



# Q10. Boolean Indexing

## Problem Statement
Create the array:

```python
[5, 12, 18, 25, 30, 7]
```

Print only the values greater than 15.

## Sample Output
```python
[18 25 30]
```


In [30]:
j = np.array([5, 12, 18, 25, 30, 7])
print(j[j>15])

[18 25 30]
