<a href="https://colab.research.google.com/github/shiva-sharma05/NumPy/blob/main/numpy_final_assign_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [20]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
arr = np.random.randint(1,10,9).reshape((3,3))
print(arr)

[[8 5 3]
 [6 4 3]
 [7 7 3]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [9]:
arr = np.array([10,20,30,40,50,60])
index = [0,2,-1]
print(arr[index])

[10 30 60]



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
arr = np.array([10,20,30,40,50,60])
print(arr[2:6])

[30 40 50 60]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
arr = np.array([10,20,30,40,50,60])
index = [0,2,4]
print(arr[index])

[10 30 50]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [16]:
arr = np.random.randint(1,50,8)
print(arr)
print(arr[arr>15])

[36 11 49 10  1 33 33  3]
[36 49 33 33]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [17]:
arr = np.array([10,20,30,40,50,60])
arr+10

array([20, 30, 40, 50, 60, 70])


# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [23]:
arr = np.array([36,11,49,10,1,33,33,3])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

176
22.0
49
1



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [28]:
num = np.array([36,11,49,10,1,33,33,3])
print(np.sort(num))

[ 1  3 10 11 33 33 36 49]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [29]:
arr1 = np.array([[2,5,7],[6,4,8]])
arr2 = np.array([[7,4,3],[4,7,2]])

print(np.vstack((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=1))

[[2 5 7]
 [6 4 8]
 [7 4 3]
 [4 7 2]]
[[2 5 7 7 4 3]
 [6 4 8 4 7 2]]
